.nh
.TH g 8

.SH NAME
.PP
g - a powerful ls


.SH SYNOPSIS
.PP
g

.PP
.RS

.nf
[--all|--la|-l]
[--byline|--bl|-1|--oneline|--single-column]
[--check-new-version]
[--checksum-algorithm|--ca]=[value]
[--checksum|--cs]
[--depth]=[value]
[--dir-first|--df]
[--file-type|--ft]
[--format]=[value]
[--full-time]
[--fuzzy|--fz|-f]
[--gid]
[--git-status-style|--gss]=[value]
[--git-status|--gs]
[--hide-git-ignore|--gi|--hgi]
[--ignore-glob|-I]=[value]
[--inode|-i]
[--lh|--human-readable]
[--list-index|--li]
[--match-glob|-M]=[value]
[--no-path-transform|--np]
[--numeric]
[--rebuild-index|--ri]
[--recurse|-R]
[--remove-index]=[value]
[--show-group|--sg]
[--show-hidden|--sh|-a]
[--show-icon|--si|--icons]
[--show-no-dir|--nd|--nodir|--no-dir]
[--show-no-ext|--sne|--noext]=[value]
[--show-only-dir|--sd|--dir|--only-dir]
[--show-only-ext|--se|--ext]=[value]
[--show-owner|--so|--author]
[--show-perm|--sp]
[--show-size|--ss]
[--show-time|--st]
[--show-total-size|--ts]
[--size-unit|--su]=[value]
[--sort-reverse|--sr]
[--sort|--SORT_FIELD]=[value]
[--theme|--th]=[value]
[--time-style]=[value]
[--time-type|--tt]=[value]
[--tree|-t]
[--uid]
[--zero|-0]
[-A|--almost-all]
[-B|--ignore-backups]
[-C|--vertical]
[-F|--classify]
[-G|--no-group]
[-d|--directory|--list-dirs]
[-g]
[-m|--comma]
[-o]
[-x|--col|--across|--horizontal]

.fi
.RE

.PP
\fBUsage\fP:

.PP
.RS

.nf
g [options] [path]

.fi
.RE


.SH GLOBAL OPTIONS
.PP
\fB--all, --la, -l\fP: show all info/use a long listing format

.PP
\fB--byline, --bl, -1, --oneline, --single-column\fP: print by line

.PP
\fB--check-new-version\fP: check if there's new release

.PP
\fB--checksum, --cs\fP: show checksum of file with algorithm: md5, sha1, sha256, sha512

.PP
\fB--checksum-algorithm, --ca\fP="": show checksum of file with algorithm: md5, sha1, sha256, sha512 (default: "sha1")

.PP
\fB--depth\fP="": limit recursive depth, negative -> infinity (default: infinity)

.PP
\fB--dir-first, --df\fP: List directories before other files

.PP
\fB--file-type, --ft\fP: likewise, except do not append '*'

.PP
\fB--format\fP="": across  -x,  commas  -m, horizontal -x, long -l, single-column -1, verbose -l, vertical -C (default: C)

.PP
\fB--full-time\fP: like -all/l --time-style=full-iso

.PP
\fB--fuzzy, --fz, -f\fP: fuzzy search

.PP
\fB--gid\fP: show gid instead of groupname [sid in windows]

.PP
\fB--git-status, --gs\fP: show git status: ? untracked, + added, ! deleted, ~ modified, | renamed, = copied, $ ignored [if git is installed]

.PP
\fB--git-status-style, --gss\fP="": git status style: colored-symbol: {? untracked, + added, - deleted, ~ modified, | renamed, = copied, ! ignored} colored-dot

.PP
\fB--hide-git-ignore, --gi, --hgi\fP: hide git ignored file/dir [if git is installed]

.PP
\fB--ignore-glob, -I\fP="": ignore Glob patterns

.PP
\fB--inode, -i\fP: show inode[linux only]

.PP
\fB--lh, --human-readable\fP: show human readable size

.PP
\fB--list-index, --li\fP: list index

.PP
\fB--match-glob, -M\fP="": match Glob patterns

.PP
\fB--no-path-transform, --np\fP: By default, .../a/b/c will be transformed to ../../a/b/c, and ~ will be replaced by homedir, using this flag to disable this feature

.PP
\fB--numeric\fP:  List numeric user and group IDs instead of name [sid in windows]

.PP
\fB--rebuild-index, --ri\fP: rebuild index

.PP
\fB--recurse, -R\fP: recurse into directories

.PP
\fB--remove-index\fP="": remove paths from index

.PP
\fB--show-group, --sg\fP: show group

.PP
\fB--show-hidden, --sh, -a\fP: show hidden files

.PP
\fB--show-icon, --si, --icons\fP: show icon

.PP
\fB--show-no-dir, --nd, --nodir, --no-dir\fP: do not show directory

.PP
\fB--show-no-ext, --sne, --noext\fP="": show file which doesn't have target ext

.PP
\fB--show-only-dir, --sd, --dir, --only-dir\fP: show directory only

.PP
\fB--show-only-ext, --se, --ext\fP="": show file which has target ext, eg: --show-only-ext=go,java

.PP
\fB--show-owner, --so, --author\fP: show owner

.PP
\fB--show-perm, --sp\fP: show permission

.PP
\fB--show-size, --ss\fP: show file/dir size

.PP
\fB--show-time, --st\fP: show time

.PP
\fB--show-total-size, --ts\fP: show total size

.PP
\fB--size-unit, --su\fP="": size unit, b, k, m, g, t, p, e, z, y, auto (default: auto)

.PP
\fB--sort, --SORT_FIELD\fP="": sort by field, default: ascending and case insensitive, field beginning with Uppercase is case sensitive, available fields: name,size,time,owner,group,extension. following \fB\fC-descend\fR to sort descending

.PP
\fB--sort-reverse, --sr\fP: reverse the order of the sort

.PP
\fB--theme, --th\fP="": apply theme \fB\fCpath/to/theme\fR

.PP
\fB--time-style\fP="": time/date format with -l, Valid timestamp styles are \fB\fCdefault',\fRiso\fB\fC,\fRlong iso\fB\fC,\fRfull-iso\fB\fC,\fRlocale\fB\fC, custom\fR+FORMAT` like date(1). (default: +%d.%b'%y %H:%M (like 02.Jan'06 15:04))

.PP
\fB--time-type, --tt\fP="": time type, mod, create, access (default: mod)

.PP
\fB--tree, -t\fP: recursively list in tree

.PP
\fB--uid\fP: show uid instead of username [sid in windows]

.PP
\fB--zero, -0\fP: end each output line with NUL, not newline

.PP
\fB-A, --almost-all\fP: do not list implied . and ..

.PP
\fB-B, --ignore-backups\fP: do not list implied entries ending with ~

.PP
\fB-C, --vertical\fP: list entries by columns (default)

.PP
\fB-F, --classify\fP: append indicator (one of */=>@|) to entries

.PP
\fB-G, --no-group\fP: in a long listing, don't print group names

.PP
\fB-d, --directory, --list-dirs\fP: list directories themselves, not their contents

.PP
\fB-g\fP: like -all/l, but do not list owner

.PP
\fB-m, --comma\fP: fill width with a comma separated list of entries

.PP
\fB-o\fP: like -all/l, but do not list group information

.PP
\fB-x, --col, --across, --horizontal\fP: list entries by lines instead of by columns

