name: gofumpt format check

on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master

permissions:
    contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 1.24.0

    - name: Install gofumpt
      run: go install mvdan.cc/gofumpt@latest

    - name: Run gofumpt and check formatting
      run: |
       output=$(gofumpt -l -extra .)
       if [ -n "$output" ]; then
         echo "$output"
         exit 1
       else
         echo "pass"
       fi
